### PR TITLE
revise '/submit-match'

### LINKED ISSUE #63: Wins to PASS after match leaves queue don't promote?
See discussion at https://github.com/gcp/leela-zero/issues/1229#issuecomment-383298609 and https://github.com/gcp/leela-zero/issues/1228#issue-316454330.

It appears a network that had sent out all pages and left pending matches queue had enough wins arrive to show PASS on the web site, but it didn't actually promote. The same SPRT()===true test is used to promote a late arrival match win and to decide to show PASS on web site. So I wonder if this is a bug that matches after the match has ended can't promote a network for some reason?

Just looking at https://github.com/gcp/leela-zero-server/blob/next/server.js#L883 I don't see why it would fail however.

### PR DESCRIPTION
**Pull request by rchs819**
Fix #63.
This is a major revision of `/submit-match`

More tests might be needed before merging

- Early SPRT pass
  - [x] Make sure match is shifted to the end of the queue when `pending_matches.length > 1`
- Early SPRT failed
  - [x] Able to promote network if the delayed results pushed to SPRT Pass 
- Server will deny duplicate sgf submission

@roy7 Please let me know if I have overlooked any logic/rules in the code

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -731,166 +731,127 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
-        });
+    if (
+        // Best network has lost
+        req.body.loserhash == best_network_hash
+        // This is not a test match
+        && !match.is_test
+        // SPRT passed OR it has reach 55% after `number_to_play` games
+        && (
+            sprt_result === true
+            || (match.game_count >= match.number_to_play && match.network1_wins / match.game_count >= 0.55)
```
Comment (roy7) [inline server.js]: Should we hard code this test as >= 400 in case we queue a match with < 400 number_to_play? We've never done that, so I'm not sure. But if we did queue for less, say 100 games, would we want to promote a 55% with 101 games using the simple 55% check without the SPRT passing?

File: server.js [hunk 2]
```diff
@@ -731,166 +731,127 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
+    // update match result 
+    if (match.network1 == req.body.winnerhash)
+        match.network1_wins++;
+    else
+        match.network1_losses++;
+
+    // save to database
+    await db.collection('matches').updateOne(
+        { _id: match._id },
+        { $set: match }
```
Comment (Mardak) [inline server.js]: Seems like concurrent match submissions could end up reading out a match from the db and after awaiting for sgfhash, both try to update to a locally computed `network1_wins/losses`. Is there a way to have the update tell the db to increment a field instead of passing it a value to set?

File: server.js (hunk 1 above)
Comment (rchs819) [reply server.js]: It looks like SPRT function has magic number 400 hard coded, then it’s better to use 400 here too

**Comment by rchs819** [comment]
@Mardak 
I've fix concurrency issue locally, but I think we still have concurrency issue globally among `/get-task` and `submit-match` (which might need another PR)

@roy7 
I've done my testing, and if @Mardak is happy with the concurrency fix, then it's ready to be merged.

File: server.js [hunk 3]
```diff
@@ -730,167 +729,131 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
+                m.network1_wins++;
+            } else {
+                m.network1_losses++;
+            }
+
+            // Check > 1 since we'll run to 400 even on a SPRT pass, but will do it at end.
+            //
+            if (sprt_result === true && pending_matches.length > 1) {
+                console.log("SPRT: Early pass unshift: " + JSON.stringify(m));
+                console.log("SPRT: Early pass post-unshift: " + JSON.stringify(pending_matches));
```
Comment (Mardak) [inline server.js]: There used to be a `pending_matches.unshift(pending_matches.splice(pending_match_index, 1));` in the first commit that got removed in https://github.com/gcp/leela-zero-server/pull/64/commits/4d57ea6a3cd9452157c93eb4714efb1dbe854e37. Shouldn't that be here to keep the passing match for later?

File: server.js [hunk 4]
```diff
@@ -730,167 +729,131 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
+
+    // get latest SPRT result
+    const sprt_result = SPRT(match.network1_wins, match.network1_losses);
+    var pending_match_index = pending_matches.findIndex(m => m._id.equals(match._id));
+
+    // match is found in pending_matches
+    if (pending_match_index >= 0) {
+        if (sprt_result === false) {
+            // remove from pending matches
+            console.log("SPRT: Early fail pop: " + JSON.stringify(pending_matches.splice(pending_match_index, 1)));
```
Comment (Mardak) [inline server.js]: A style issue: probably best to splice outside of the `console.log` to avoid someone thinking the message has no sideeffects.

File: server.js [hunk 5]
```diff
@@ -730,167 +729,131 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
-            //
-            if (match && !match.is_test && ( (SPRT(match.network1_wins, match.network1_losses) === true) || (match.game_count >= 400 && match.network1_wins / match.game_count >= 0.55) ) ) {
-                fs.copyFileSync(__dirname + '/network/' + req.body.winnerhash + '.gz', __dirname + '/network/best-network.gz');
-                console.log("New best network copied from (normal check): " + __dirname + '/network/' + req.body.winnerhash + '.gz');
-            }
-        }).catch( err => {
-            console.log("ERROR: " + req.body.winnerhash + " " + best_network_hash + " " + req.body.options_hash);
-            console.log("ERROR: Couldn't check for new best network: " + err);
-        });
+    var best_network_hash = await get_best_network_hash();
```
Comment (Mardak) [inline server.js]: It looks like it's possible for two concurrent wins to both await the best hash to then both decide to promote. Although in this case, it will just end up copying the file twice, so it's probably fine.

**Comment by Mardak** [comment]
The code looks mostly fine although I haven't tested myself, and I'm not familiar with the db methods, etc.

It looks like an early pass doesn't actually get back in the queue though.

**Comment by rchs819** [comment]
@Mardak I've made some changes according to you comments. Thanks for the review.

File: server.js [hunk 6]
```diff
@@ -730,167 +729,136 @@ app.post('/submit-match',  asyncMiddleware( async (req, res, next) => {
...
+    if (match.network1 == req.body.winnerhash)
+        $inc.network1_wins = 1;
+    else
+        $inc.network1_losses = 1;
+
+    // save to database using $inc and get modified document
+    match = (await db.collection("matches").findOneAndUpdate(
+        { _id: match._id },
+        { $inc: $inc },
+        { returnOriginal: false }  // return modified document
```
Comment (Mardak) [inline server.js]: The latest 3.6 documentation seems to have a `returnNewDocument` but not a `returnOriginal`? And since `findOneAndUpdate` was added in 3.2, it looks like it was always `returnNewDocument` ??

https://docs.mongodb.com/v3.2/reference/method/db.collection.findOneAndUpdate/
https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/ (3.6)

Looks like this change requires updating package.json.

**Comment by Mardak** [comment]
The code looks okay for concurrency issues. Not sure what's @roy7's approach for testing these changes on a test server just to double check before pushing to the main production endpoint. But this change probably wants extra testing.

File: server.js (hunk 5 above)
Comment (roy7) [reply server.js]: This seems okay to ignore. The odds we have two promotes happen vs same best network back to back so quickly that get_best_network_hash can't return fast enough seems... unlikely. :)
